export const GET_POINTS_REQUEST = 'GET_POINTS_REQUEST'
export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS'
export const GET_POINTS_ERROR = 'GET_POINTS_ERROR'

export const GET_LIST_CARDS_REQUEST = "GET_LIST_CARDS_REQUEST"
export const GET_LIST_CARDS_SUCCESS = "GET_LIST_CARDS_SUCCESS"
export const GET_LIST_CARDS_ERROR = "GET_LIST_CARDS_ERROR"

export const GET_RULES_REQUEST = "GET_RULES_REQUEST"
export const GET_RULES_SUCCESS = "GET_RULES_SUCCESS"
export const GET_RULES_ERROR = "GET_RULES_ERROR"

export const SET_GAME_STATUS = "SET_GAME_STATUS"

export const GET_GAME_HANDS_REQUEST = "GET_GAME_HANDS_REQUEST"
export const GET_GAME_HANDS_SUCCESS = "GET_GAME_HANDS_SUCCESS"
export const GET_GAME_HANDS_ERROR = "GET_GAME_HANDS_ERROR"

export const STORE_PARTNER_BET = "STORE_PARTNER_BET"
export const STORE_PLAYER_BET = "STORE_PLAYER_BET"
export const STORE_ENNEMY_BET = "STORE_ENNEMY_BET"

export const GET_AI_BET_REQUEST = "GET_AI_BET_REQUEST"
export const GET_AI_BET_ERROR = "GET_AI_BET_ERROR"
export const GET_AI_BET_SUCCESS = "GET_AI_BET_SUCCESS"

export const PLAY_CARD = "PLAY_CARD"

export const CAN_PLAY_REQUEST = "CAN_PLAY_REQUEST"
export const CAN_PLAY_SUCCESS = "CAN_PLAY_SUCCESS"
export const CAN_PLAY_ERROR = "CAN_PLAY_ERROR"

export const GET_AI_MOVE_REQUEST = "GET_AI_MOVE_REQUEST"
export const GET_AI_MOVE_SUCCESS = "GET_AI_MOVE_SUCCESS"
export const GET_AI_MOVE_ERROR = "GET_AI_MOVE_ERROR"

export const GET_CURRENT_FOLD_RESULT_REQUEST = "GET_CURRENT_FOLD_RESULT_REQUEST"
export const GET_CURRENT_FOLD_RESULT_ERROR = "GET_CURRENT_FOLD_RESULT_ERROR"
export const GET_CURRENT_FOLD_RESULT_SUCCESS = "GET_CURRENT_FOLD_RESULT_SUCCESS"
