export const GET_POINTS_REQUEST = 'GET_POINTS_REQUEST'
export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS'
export const GET_POINTS_ERROR = 'GET_POINTS_ERROR'

export const GET_LIST_CARDS_REQUEST = "GET_LIST_CARDS_REQUEST"
export const GET_LIST_CARDS_SUCCESS = "GET_LIST_CARDS_SUCCESS"
export const GET_LIST_CARDS_ERROR = "GET_LIST_CARDS_ERROR"

export const GET_RULES_REQUEST = "GET_RULES_REQUEST"
export const GET_RULES_SUCCESS = "GET_RULES_SUCCESS"
export const GET_RULES_ERROR = "GET_RULES_ERROR"

export const SET_GAME_STATUS = "SET_GAME_STATUS"

export const GET_GAME_HANDS_REQUEST = "GET_GAME_HANDS_REQUEST"
export const GET_GAME_HANDS_SUCCESS = "GET_GAME_HANDS_SUCCESS"
export const GET_GAME_HANDS_ERROR = "GET_GAME_HANDS_ERROR"
